import { type NextPage } from "next";
import { signIn, useSession, signOut } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const mutation = api.group.add.useMutation();
  const ownGroups = api.group.getAll.useQuery();
  if (status === "loading") {
    return <span>Loading...</span>;
  }

  if (!session) {
    return <button onClick={() => signIn("google")}>Sign In</button>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Whatsup</h1>
      <button onClick={() => signOut()}>Sign Out</button>
      <button
        onClick={() => {
          mutation.mutate();
        }}
      >
        Create
      </button>
      {JSON.stringify(session)}
      <p className="my-32">{JSON.stringify(ownGroups.data)}</p>
    </>
  );
};

export default Home;
